#!/bin/bash
################################################################################
# config - Shared configuration for Tux Manager packaging scripts
################################################################################

# Application metadata
APP_NAME="tux-manager"
APP_VERSION="1.0.3"
MAINTAINER="Petr Bena <petr@bena.rocks>"
DESCRIPTION="Tux Manager - Linux system monitor inspired by Windows Task Manager"
APP_HOMEPAGE_URL="https://github.com/benapetr/TuxManager"

# Icon path (relative to project root)
APP_ICON_PATH="src/tux_manager_icon.svg"
